baseURL = "https://ibrahim5823.github.io/"
languageCode = "en-us"
theme = "almeida-cv"
title = "Ibrahim - CV"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#001440"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 2
